FROM maven:3.9.10-sapmachine-21

COPY target/BatchMessageConsumer-1.0-jar-with-dependencies.jar /kafka-apps/BatchMessageConsumer.jar

WORKDIR /kafka-apps

ENTRYPOINT ["java", "-jar"]
CMD ["BatchMessageConsumer.jar"]