version: "3.9"

services:
  producer:
    deploy:
      replicas: 2
    image: docker.io/xillah/kafka:producer@sha256:499904d3f62b9160cd2f78dba6ae1840f97baca28bac8144d6d2e98ea76b31de
    environment:
      - BOOTSTRAP_SERVERS_CONFIG=kafka-0:9092
      - KAFKA_TOPIC_NAME=supertopic
      - MESSAGE_PERIOD=500
    # command: ["java", "-jar", "/java-proj/kafkaProducer/target/kafkaProducer-1.0-jar-with-dependencies.jar"]
    volumes: 
      - /home/yelena/IntellijIDEA:/java-proj 
    # command: ["sleep", "99d"]
  single_consumer:
    deploy:
      replicas: 2
    image: docker.io/xillah/kafka:single-consumer@sha256:5160e28eec3c21b289592b119efdcb613207ba9c1fc727472ee86b9e0e7fd798
    # command: ["sleep", "99d"]
    # command: ["java", "-jar", "/java-proj/SingleMessageConsumer/target/SingleMessageConsumer-1.0-jar-with-dependencies.jar"]
    environment:
      - BOOTSTRAP_SERVERS_CONFIG=kafka-0:9092
      - KAFKA_TOPIC_NAME=supertopic
      - CONSUMER_GROUP_NAME=single
    volumes: 
      - /home/yelena/IntellijIDEA:/java-proj   
  batch_consumer:
    deploy:
      replicas: 2
    image: docker.io/xillah/kafka:batch-consumer@sha256:9e47483e34ef6c44b865fdb0cbf86368d5cd455a3959c43239e0364285d65299
    # command: ["sleep", "99d"]
    # command: ["java", "-jar", "/java-proj/BatchMessageConsumer/target/BatchMessageConsumer-1.0-jar-with-dependencies.jar"]
    environment:
      - BOOTSTRAP_SERVERS_CONFIG=kafka-0:9092
      - KAFKA_TOPIC_NAME=supertopic
      - CONSUMER_GROUP_NAME=batch
      - MAX_POLL_RECORDS_CONFIG=10
      - FETCH_MIN_BYTES_CONFIG=800
      - FETCH_MAX_WAIT_MS_CONFIG=50000
    volumes: 
      - /home/yelena/IntellijIDEA:/java-proj 
networks:
  kafka_deploy_default:
    driver: bridge
