version: "3.9"

services:
  producer:
    deploy:
      replicas: 2
    image: docker.io/xillah/kafka:producer@sha256:499904d3f62b9160cd2f78dba6ae1840f97baca28bac8144d6d2e98ea76b31de
    environment:
      - BOOTSTRAP_SERVERS_CONFIG=kafka-0:9092 # Kafka bootstrap server
      - KAFKA_TOPIC_NAME=supertopic # Topic for subscription
      - MESSAGE_PERIOD=500 # How often generate simple messages in milliseconds
  single_consumer:
    deploy:
      replicas: 2
    image: docker.io/xillah/kafka:single-consumer@sha256:5160e28eec3c21b289592b119efdcb613207ba9c1fc727472ee86b9e0e7fd798
    environment:
      - BOOTSTRAP_SERVERS_CONFIG=kafka-0:9092 # Kafka bootstrap server
      - KAFKA_TOPIC_NAME=supertopic # Topic for subscription
      - CONSUMER_GROUP_NAME=single  # Name to assign to comsumer group
  batch_consumer:
    deploy:
      replicas: 2
    image: docker.io/xillah/kafka:batch-consumer@sha256:9e47483e34ef6c44b865fdb0cbf86368d5cd455a3959c43239e0364285d65299
    environment:
      - BOOTSTRAP_SERVERS_CONFIG=kafka-0:9092 # Kafka bootstrap server
      - KAFKA_TOPIC_NAME=supertopic # Topic for subscription
      - CONSUMER_GROUP_NAME=batch # Name to assign to comsumer group
      - MAX_POLL_RECORDS_CONFIG=10 # Max amount of massages in one poll
      - FETCH_MIN_BYTES_CONFIG=800 # Min required bytes to form a batch for this consumer
      - FETCH_MAX_WAIT_MS_CONFIG=50000 # Time to wait for a batch
networks:
  kafka_deploy_default:
    driver: bridge
